import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-950 text-zinc-100`}>
        <header className="border-b border-zinc-800">
          <nav className="mx-auto max-w-5xl p-4 flex gap-4">
            <Link href="/clientes" className="text-base text-zinc-300 hover:text-white">Clientes</Link>
            <Link href="/loteos" className="text-base text-zinc-300 hover:text-white">Loteos</Link>
            <Link href="/propiedades" className="text-base text-zinc-300 hover:text-white">Propiedades</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
